insert into uf (uf, name, created_at, updated_at) values
('AC', 'Acre', now(), null),
('AL', 'Alagoas', now(), null),
('AP', 'Amapá', now(), null),
('AM', 'Amazonas', now(), null),
('BA', 'Bahia', now(), null),
('CE', 'Ceará', now(), null),
('DF', 'Distrito Federal', now(), null),
('ES', 'Espirito Santo', now(), null),
('GO', 'Goiás', now(), null),
('MA', 'Maranhão', now(), null),
('MT', 'Mato Grosso', now(), null),
('MS', 'Mato Grosso do Sul', now(), null),
('MG', 'Minas Gerais', now(), null),
('PA', 'Pará', now(), null),
('PB', 'Paraíba', now(), null),
('PR', 'Paraná', now(), null),
('PE', 'Pernambuco', now(), null),
('PI', 'Piauí', now(), null),
('RJ', 'Rio de Janeiro', now(), null),
('RN', 'Rio Grande do Norte', now(), null),
('RS', 'Rio Grande do Sul', now(), null),
('RO', 'Rondônia', now(), null),
('RR', 'Roraima', now(), null),
('SC', 'Santa Catarina', now(), null),
('SP', 'São Paulo', now(), null),
('SE', 'Sergipe', now(), null),
('TO', 'Tocantis', now(), null)