insert into profession (profession, created_at, updated_at) values
('Analista de Sistemas', now(), null),
('Atentende de Telemarketing', now(), null),
('Administrador', now(), null),
('Advogado', now(), null),
('Agrônomo', now(), null),
('Arquiteto e Urbanista', now(), null),
('Assistente Social', now(), null),
('Biologo', now(), null),
('Biomedico', now(), null),
('Biotecnologista', now(), null),
('Contador', now(), null),
('Designer Grafico', now(), null),
('Designer de Moda', now(), null),
('Economista', now(), null),
('Enfermeiro', now(), null),
('Engenheiro Ambiental', now(), null),
('Engenheiro Civil', now(), null),
('Engenheiro Eletricista', now(), null),
('Engenheiro Mecânico', now(), null),
('Engenheiro Produção', now(), null),
('Engenheiro Quimico', now(), null),
('Estudante', now(), null),
('Empresário', now(), null),
('Farmacêutico', now(), null),
('Fisioterapeuta', now(), null),
('Médico', now(), null),
('Motorista', now(), null),
('Nutricionista', now(), null),
('Odontólogo', now(), null),
('Pedagogo', now(), null),
('Programador', now(), null),
('Psicologo', now(), null),
('Secretaria', now(), null),
('Turismologo', now(), null),
('Veterinário', now(), null),
('Zootecnista', now(), null),
('Outros não Especificados', now(), null)